<?xml version="1.0"?>

<robot name="rsv_balance" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rsv_balance_description)/urdf/robot.urdf.xacro" />
  
  <!-- Common Gazebo definitions and configurations for the platform's base -->
  <xacro:include filename="$(find rsv_balance_gazebo)/urdf/balance.gazebo.xacro" />

  <gazebo reference="rod_link">
    <material>Gazebo/White</material>
  </gazebo>
  <gazebo reference="weight_link">
    <material>Gazebo/Black</material>
  </gazebo>
  
  <gazebo>
    <plugin name="rsv_balance_controller" filename="libgazebo_rsv_balance.so">
      <!-- ROS node configurations -->
<!--  <rosDebugLevel>Debug</rosDebugLevel> -->
<!--  <robotNamespace></robotNamespace> -->
      <commandTopic>cmd_vel</commandTopic>
      <baseFrameId>base_link</baseFrameId>
      <publishOdomTF>true</publishOdomTF>
      <odomFrameId>odom</odomFrameId>
      <odomSource>world</odomSource>
      <odomTopic>odom</odomTopic>
      <publishWheelJointState>true</publishWheelJointState>
      <!-- Platform specific configurations -->
      <startMode>balance</startMode>
      <publishState>true</publishState>
      <publishStateRate>1</publishStateRate>
      <publishDiagnosticsRate>1</publishDiagnosticsRate>
      <wheelSeparation>${base_width+2.*wheel_width/2.}</wheelSeparation>
      <wheelRadius>${wheel_radius}</wheelRadius>
      <leftJoint>base_to_left_wheel</leftJoint>
      <rightJoint>base_to_right_wheel</rightJoint>   
      <!-- Control specific configurations -->
      <updateRate>100</updateRate>
    </plugin>
  </gazebo>
</robot>
